### ISSUE TITLE
Failure building icewm 2.2.0 on Linux

### ISSUE THREAD

**Issue by timtas** [ice-wm/icewm#43]
Upon linking, I get:

/usr/bin/ld: /tmp/icewm.7NJrdK.ltrans0.ltrans.o: in function `YDialog::getGradient()':
<artificial>:(.text+0x200): undefined reference to `dialogbackPixbuf'
/usr/bin/ld: /tmp/icewm.7NJrdK.ltrans0.ltrans.o: in function `YFrameWindow::canRollup() const [clone .lto_priv.0]':
<artificial>:(.text+0x441): undefined reference to `hideTitleBarWhenMaximized'
/usr/bin/ld: <artificial>:(.text+0x46e): undefined reference to `wsTitleBar'
/usr/bin/ld: /tmp/icewm.7NJrdK.ltrans0.ltrans.o: in function `non-virtual thunk to YFrameWindow::canRollup() const':
<artificial>:(.text+0x511): undefined reference to `hideTitleBarWhenMaximized'
/usr/bin/ld: <artificial>:(.text+0x548): undefined reference to `wsTitleBar'
/usr/bin/ld: /tmp/icewm.7NJrdK.ltrans0.ltrans.o: in function `YArray<YFrameWindow*>::~YArray()':
<artificial>:(.text+0x9f7): undefined reference to `vtable for YBaseArray'

I have tried to build using:

mkdir build &&
cd    build &&

cmake -DCMAKE_INSTALL_PREFIX=/opt/X11 \
      -DCMAKE_BUILD_TYPE=Release  \
      -DCFGDIR=/etc               \
      -DENABLE_LTO=ON             \
      -DCONFIG_GDK_PIXBUF_XLIB=ON \
      -DCONFIG_IMLIB2=OFF \
      -DDOCDIR=/usr/share/doc/icewm  \
      .. &&
make

which has worked fine with icewm 2.1.2

**Comment by timtas** [comment]
Sorry, this seems to have been due to a broken link of /usr/lib/bfd-plugins/liblto_plugin.so. Was no problem in earlier releases, but went away after fixing the link.
